SmartStrategy/SmartStrategy/urls.py
from django.contrib import admin
from django.urls import path, re_path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('authentication/', include(('authentication.urls', 'authentication'), namespace = 'authentication')),
    path('', include(('strategy.urls', 'strategy'), namespace = 'strategy')),
]

SmartStrategy/authentication/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register_view, name='register'),
]

SmartStrategy/strategy/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home_view, name='home'),
    path('info/', views.info_view, name='info'),
    path('job_list/', views.job_list_view, name='job_list'),
    path('job_task/(?P<event_name>[0-9]+)/\\Z/', views.job_task_view, name='job_task'),
    path('signedup/<event_name>/<task_name>/', views.signedup_view, name='signedup'),
]

SmartStrategy/authentication/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Volunteer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    country = models.CharField(max_length=255)
    city = models.CharField(max_length=255)
    phone_number = models.CharField(max_length=255)
    skills = models.CharField(max_length=255, default="")
    #put keywords


class Organisation(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    username = models.CharField(max_length=255, unique=True)
    

SmartStrategy/strategy/models.py
from django.db import models

# Create your models here.

SmartStrategy/authentication/forms.py
#create django login form
from django import forms

form_attr = {"class" : "input-input input"}

class VolunteerRegisterForm(forms.Form):
    email = forms.EmailField(widget=forms.EmailInput(attrs={"class" : "input-input input", "placeholder" : "Email"}))
    full_name = forms.CharField(widget=forms.TextInput(attrs={"class" : "input-input input", "placeholder" : "Full Name"}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={"class" : "input-input input", "placeholder" : "Password"}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs=form_attr))
    country = forms.CharField(widget=forms.TextInput(attrs={"class" : "input-input input", "placeholder" : "Country"}))
    city = forms.CharField(widget=forms.TextInput(attrs=form_attr))
    phone_number = forms.CharField( widget=forms.TextInput(attrs={"class" : "input-input input", "placeholder" : "Phone Number"}))
    skills = forms.CharField( widget=forms.TextInput(attrs={ "class" : "input-input input", "placeholder" : "Skills"}))

class VolunteerLoginForm(forms.Form):
    email = forms.EmailField( widget=forms.EmailInput(attrs={"class" : "input-input input", "placeholder" : "Email"}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={"class" : "input-input input", "placeholder" : "Password"}))

SmartStrategy/authentication/views.py
from django.shortcuts import render, redirect
from django.views.generic import View
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from .models import Volunteer
from .forms import VolunteerRegisterForm, VolunteerLoginForm
# Create your views here.

def login_view(request):
    if request.user.is_authenticated:
        return redirect('strategy:home')
    context = {
        'form': VolunteerLoginForm()
    }
    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')
        user = authenticate(request, username=email, password=password)
        if user is not None:
            login(request, user)
            return redirect('strategy:home')
        else:
            context['error'] = 'Username or password is incorrect'
    return render(request, 'authentication/login.html', context)       

def logout_view(request):
    logout(request)
    return redirect('strategy:home')

def register_view(request):
    if request.user.is_authenticated:
        return redirect('strategy:home')
    
    context = {
        'form': VolunteerRegisterForm()
    }
    if request.method == 'POST':
       #register user
        form = VolunteerRegisterForm(request.POST)
        user = User.objects.create_user(
            username=form.data['email'],
            email=form.data['email'],
            password=form.data['password'],
            first_name=form.data['full_name'],
        )
        Volunteer.objects.create(
            user=user,
            country=form.data['country'],
            city=form.data['country'],
            phone_number=form.data['country'],
        )
        login(request, user)
        return redirect('strategy:home')
    return render(request, 'authentication/register.html', context)

SmartStrategy/strategy/views.py
from django.shortcuts import render, redirect
from .processing_jobs.backend import backend
import requests

#create home view 
def home_view(request):

    return render(request, 'home.html')

def info_view(request):
    return render(request, 'jobs/info.html')

def job_list_view(request):
    user = request.user
    if not user.is_authenticated:
        return redirect('authentication:register')
    #fetch data from red cross API
    url = 'https://goadmin.ifrc.org/api/v2/event/?is_featured=1'
    response = requests.get(url)
    response = response.json()
    events = response['results']
    for event in events:
        if 'Earthquake' in event['name']:
            event['image'] = 'media/earthquake.png'
        elif 'HUNGER' in event['name']:
            event['image'] = 'media/famine.png'
        elif 'COVID' in event['name'] or 'Cholera' in event['name']:
            event['image'] = 'media/covid.png'
        elif 'Ukraine' in event['name']:
            event['image'] = 'media/war.png'
        else:
            event['image'] = 'media/rectangle121810-c1qc-300h.png'

    context = {
        'events': events,
    } 
    return render(request, 'jobs/jobs.html', context)



def job_task_view(request, event_name):
    user = request.user
    if not user.is_authenticated:
        return redirect('authentication:register')
    #generate job details based on keywords
    tasks = [
        {'title': task[0], 'description': task[1]} for task in backend(3691, event_name) if len(task) > 1
    ]
    for task in tasks:
        if 'Shelter' in task['title']:
            task['image'] = 'media/shelter.png'
        elif 'Medical' in task['title']:
            task['image'] = 'media/medical.png'
        elif 'Livelihood' in task['title']:
            task['image'] = 'media/livelihood.png'
        elif 'Clothing' in task['title']:
            task['image'] = 'media/clothing.png'
        else:
            task['image'] = 'media/rectangle121810-c1qc-300h.png'
    context = {
        'event_name': event_name,
        'tasks': tasks,
    }

    return render(request, 'jobs/tasks.html', context)


def signedup_view(request, event_name, task_name):
    user = request.user
    if not user.is_authenticated:
        return redirect('authentication:register')
    context = {
        'event_name': event_name,
        'task_name': task_name,
    }
    return render(request, 'jobs/signedup.html', context)

SmartStrategy/templates/components/button.html
<div>
    <link href="{% static 'css/button.css' %}" rel="stylesheet" />
    <div class="button-container">
        <a href="sign-up.html" class="button-button">
            <span class="button-text"><span>Volunteer</span></span>
        </a>
    </div>
</div>

SmartStrategy/templates/components/component.html
<div>
    <link href="{% static 'css/component.css' %}" rel="stylesheet" />
    <div class="component-container"></div>
</div>

SmartStrategy/templates/home.html
<html lang="english">
{% load static %}
    <head>
        <title>Home</title>
        <meta property="og:title" content="exported project" />
        <meta
            name="viewport"
            content="width=device-width, initial-scale=1.0"
        />
        <meta charset="utf-8" />
        <meta property="twitter:card" content="summary_large_image" />
        <link rel="icon" href="{% static 'media/favicon.png' %}" />

        <style data-tag="reset-style-sheet">
            html {
                line-height: 1.15;
            }
            body {
                margin: 0;
            }
            * {
                box-sizing: border-box;
                border-width: 0;
                border-style: solid;
            }
            p,
            li,
            ul,
            pre,
            div,
            h1,
            h2,
            h3,
            h4,
            h5,
            h6,
            figure,
            blockquote,
            figcaption {
                margin: 0;
                padding: 0;
            }
            button {
                background-color: transparent;
            }
            button,
            input,
            optgroup,
            select,
            textarea {
                font-family: inherit;
                font-size: 100%;
                line-height: 1.15;
                margin: 0;
            }
            button,
            select {
                text-transform: none;
            }
            button,
            [type='button'],
            [type='reset'],
            [type='submit'] {
                -webkit-appearance: button;
            }
            button::-moz-focus-inner,
            [type='button']::-moz-focus-inner,
            [type='reset']::-moz-focus-inner,
            [type='submit']::-moz-focus-inner {
                border-style: none;
                padding: 0;
            }
            button:-moz-focus,
            [type='button']:-moz-focus,
            [type='reset']:-moz-focus,
            [type='submit']:-moz-focus {
                outline: 1px dotted ButtonText;
            }
            a {
                color: inherit;
                text-decoration: inherit;
            }
            input {
                padding: 2px 4px;
            }
            img {
                display: block;
            }
            html {
                scroll-behavior: smooth;
            }
        </style>
        <style data-tag="default-style-sheet">
            html {
                font-family: Inter;
                font-size: 16px;
            }

            body {
                font-weight: 400;
                font-style: normal;
                text-decoration: none;
                text-transform: none;
                letter-spacing: normal;
                line-height: 1.15;
                color: var(--dl-color-gray-black);
                background-color: var(--dl-color-gray-white);
            }
        </style>
        <link
            rel="stylesheet"
            href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&amp;display=swap"
            data-tag="font"
        />
        <link
            rel="stylesheet"
            href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&amp;display=swap"
            data-tag="font"
        />
        <link href="{% static 'css/style.css' %}" rel="stylesheet" />
    </head>
    <body>
        <div>
            <link
                href="{% static 'css/home.css' %}"
                rel="stylesheet"
            />

            <div class="home-container">
                <nav class="navbar-navbar navbar-root-class-name">
                    <a href="{% url 'strategy:home' %}" class="navbar-navlink">
                        <div class="navbar-frame5">
                            <img
                                alt="image41032"
                                src="{% static 'media/image41032-ng39-200w.png' %}"
                                class="navbar-image4"
                            />
                            <img
                                alt="Line11032"
                                src="{% static 'media/line11032-r54d.svg' %}"
                                class="navbar-line1"
                            />
                            <img
                                alt="image31032"
                                src="{% static 'media/image31032-x22b-200h.png' %}"
                                class="navbar-image3"
                            />
                        </div>
                    </a>
                    <div class="navbar-menu">
                        <a href="{% url 'strategy:job_list' %}" class="navbar-menuitem">
                            <span class="navbar-text"
                                ><span>Emergencies</span></span
                            >
                        </a>
                        <a href="{% url 'strategy:info' %}"  class="navbar-menuitem1">
                            <span class="navbar-text2"
                                ><span>How it works</span></span
                            >
                        </a>
                        <button class="navbar-button">
                            <img
                                alt="Rectangle171031"
                                src="{% static 'media/rectangle171031-rxgd-200h.png' %}"
                                class="navbar-rectangle17"
                            />
                            <span class="navbar-text4">
                                {% if user.is_authenticated %}
                                <a
                                    href="{% url 'authentication:logout' %}"
                                    >Log out</a
                                >
                                {% else %}
                                <a
                                    href="{% url 'authentication:login' %}"
                                    >Log in</a
                                >
                                {% endif %}
                            </span>
                        </button>
                    </div>
                </nav>
                <div class="home-frame14">
                    <span class="home-text"
                        >Take Part in The Response</span
                    >
                    <span class="home-text1">
                        <span>
                            Help IFRC in operations in your area and
                            around the world
                        </span>
                    </span>
                    <div class="button-container">
                        <a
                            href="{% url 'strategy:job_list'%}"
                            class="button-button"
                        >
                            <span class="button-text"
                                ><span>Volunteer</span></span
                            >
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>

SmartStrategy/templates/jobs/info.html
<html lang="english">
{% load static %}
    <head>
        <title>Info</title>
        <meta property="og:title" content="exported project" />
        <meta
            name="viewport"
            content="width=device-width, initial-scale=1.0"
        />
        <meta charset="utf-8" />
        <meta property="twitter:card" content="summary_large_image" />
        <link rel="icon" href="{% static 'media/favicon.png' %}" />

        <style data-tag="reset-style-sheet">
            html {
                line-height: 1.15;
            }
            body {
                margin: 0;
            }
            * {
                box-sizing: border-box;
                border-width: 0;
                border-style: solid;
            }
            p,
            li,
            ul,
            pre,
            div,
            h1,
            h2,
            h3,
            h4,
            h5,
            h6,
            figure,
            blockquote,
            figcaption {
                margin: 0;
                padding: 0;
            }
            button {
                background-color: transparent;
            }
            button,
            input,
            optgroup,
            select,
            textarea {
                font-family: inherit;
                font-size: 100%;
                line-height: 1.15;
                margin: 0;
            }
            button,
            select {
                text-transform: none;
            }
            button,
            [type='button'],
            [type='reset'],
            [type='submit'] {
                -webkit-appearance: button;
            }
            button::-moz-focus-inner,
            [type='button']::-moz-focus-inner,
            [type='reset']::-moz-focus-inner,
            [type='submit']::-moz-focus-inner {
                border-style: none;
                padding: 0;
            }
            button:-moz-focus,
            [type='button']:-moz-focus,
            [type='reset']:-moz-focus,
            [type='submit']:-moz-focus {
                outline: 1px dotted ButtonText;
            }
            a {
                color: inherit;
                text-decoration: inherit;
            }
            input {
                padding: 2px 4px;
            }
            img {
                display: block;
            }
            html {
                scroll-behavior: smooth;
            }
        </style>
        <style data-tag="default-style-sheet">
            html {
                font-family: Inter;
                font-size: 16px;
            }

            body {
                font-weight: 400;
                font-style: normal;
                text-decoration: none;
                text-transform: none;
                letter-spacing: normal;
                line-height: 1.15;
                color: var(--dl-color-gray-black);
                background-color: var(--dl-color-gray-white);
            }
        </style>
        <link
            rel="stylesheet"
            href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&amp;display=swap"
            data-tag="font"
        />
        <link
            rel="stylesheet"
            href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&amp;display=swap"
            data-tag="font"
        />
        <link href="{% static 'css/style.css' %}" rel="stylesheet" />
    </head>
    <body>
        <div>
            <link
                href="{% static 'css/info.css' %}"
                rel="stylesheet"
            />

            <div class="home-container">
                <nav class="navbar-navbar navbar-root-class-name">
                    <a href="{% url 'strategy:home' %}" class="navbar-navlink">
                        <div class="navbar-frame5">
                            <img
                                alt="image41032"
                                src="{% static 'media/image41032-ng39-200w.png' %}"
                                class="navbar-image4"
                            />
                            <img
                                alt="Line11032"
                                src="{% static 'media/line11032-r54d.svg' %}"
                                class="navbar-line1"
                            />
                            <img
                                alt="image31032"
                                src="{% static 'media/image31032-x22b-200h.png' %}"
                                class="navbar-image3"
                            />
                        </div>
                    </a>
                    <div class="navbar-menu">
                        <a href="{% url 'strategy:job_list' %}" class="navbar-menuitem">
                            <span class="navbar-text"
                                ><span>Emergencies</span></span
                            >
                        </a>
                        <a href="{% url 'strategy:info' %}"  class="navbar-menuitem1">
                            <span class="navbar-text2"
                                ><span>How it works</span></span
                            >
                        </a>
                        <button class="navbar-button">
                            <img
                                alt="Rectangle171031"
                                src="{% static 'media/rectangle171031-rxgd-200h.png' %}"
                                class="navbar-rectangle17"
                            />
                            <span class="navbar-text4">
                                {% if user.is_authenticated %}
                                <a
                                    href="{% url 'authentication:logout' %}"
                                    >Log out</a
                                >
                                {% else %}
                                <a
                                    href="{% url 'authentication:login' %}"
                                    >Log in</a
                                >
                                {% endif %}
                            </span>
                        </button>
                    </div>
                </nav>
                <div class="home-frame14">
                    <span class="home-text"
                        >How does it work?</span
                    >
                    <span class="home-text1">
                        <span>
                            We connect volunteers with people in need of assistance during emergencies,
                             providing a platform for individuals and organizations to find and communicate with each other.
                              It enables volunteers to offer their time, skills, and resources to support those affected by emergencies.
                        </span>
                    </span>
                    <div class="button-container">
                        <a
                            href="{% url 'strategy:home'%}"
                            class="button-button"
                        >
                            <span class="button-text"
                                ><span>Let's do this</span></span
                            >
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>

SmartStrategy/templates/jobs/jobs.html
<!DOCTYPE html>
<html lang="english">
{% load static %}
    <head>
        <title>Jobs</title>
        <meta property="og:title" content="Jobs - exported project" />
        <meta
            name="viewport"
            content="width=device-width, initial-scale=1.0"
        />
        <meta charset="utf-8" />
        <meta property="twitter:card" content="summary_large_image" />
        <link rel="icon" href="{% static 'media/favicon.png' %}" />

        <style data-tag="reset-style-sheet">
            html {
                line-height: 1.15;
            }
            body {
                margin: 0;
            }
            * {
                box-sizing: border-box;
                border-width: 0;
                border-style: solid;
            }
            p,
            li,
            ul,
            pre,
            div,
            h1,
            h2,
            h3,
            h4,
            h5,
            h6,
            figure,
            blockquote,
            figcaption {
                margin: 0;
                padding: 0;
            }
            button {
                background-color: transparent;
            }
            button,
            input,
            optgroup,
            select,
            textarea {
                font-family: inherit;
                font-size: 100%;
                line-height: 1.15;
                margin: 0;
            }
            button,
            select {
                text-transform: none;
            }
            button,
            [type='button'],
            [type='reset'],
            [type='submit'] {
                -webkit-appearance: button;
            }
            button::-moz-focus-inner,
            [type='button']::-moz-focus-inner,
            [type='reset']::-moz-focus-inner,
            [type='submit']::-moz-focus-inner {
                border-style: none;
                padding: 0;
            }
            button:-moz-focus,
            [type='button']:-moz-focus,
            [type='reset']:-moz-focus,
            [type='submit']:-moz-focus {
                outline: 1px dotted ButtonText;
            }
            a {
                color: inherit;
                text-decoration: inherit;
            }
            input {
                padding: 2px 4px;
            }
            img {
                display: block;
            }
            html {
                scroll-behavior: smooth;
            }
        </style>
        <style data-tag="default-style-sheet">
            html {
                font-family: Inter;
                font-size: 16px;
            }

            body {
                font-weight: 400;
                font-style: normal;
                text-decoration: none;
                text-transform: none;
                letter-spacing: normal;
                line-height: 1.15;
                color: var(--dl-color-gray-black);
                background-color: var(--dl-color-gray-white);
            }
        </style>
        <link
            rel="stylesheet"
            href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&amp;display=swap"
            data-tag="font"
        />
        <link
            rel="stylesheet"
            href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&amp;display=swap"
            data-tag="font"
        />
        <link href="{% static 'css/style.css' %}" rel="stylesheet" />
    </head>
    <body>
        <div>
            <link
                href="{% static 'css/jobs.css' %}"
                rel="stylesheet"
            />

            <div class="jobs-container">
                <nav class="navbar-navbar navbar-root-class-name1">
                    <a href="{% url 'strategy:home' %}" class="navbar-navlink">
                        <div class="navbar-frame5">
                            <img
                                alt="image41032"
                                src="{% static 'media/image41032-ng39-200w.png' %}"
                                class="navbar-image4"
                            />
                            <img
                                alt="Line11032"
                                src="{% static 'media/line11032-r54d.svg' %}"
                                class="navbar-line1"
                            />
                            <img
                                alt="image31032"
                                src="{% static 'media/image31032-x22b-200h.png' %}"
                                class="navbar-image3"
                            />
                        </div>
                    </a>
                    <div class="navbar-menu">
                        <a href="{% url 'strategy:job_list' %}" class="navbar-menuitem">
                            <span class="navbar-text"
                                ><span>Emergencies</span></span
                            >
                        </a>
                        <a href="{% url 'strategy:info' %}"  class="navbar-menuitem1">
                            <span class="navbar-text2"
                                ><span>How it works</span></span
                            >
                        </a>
                        <button class="navbar-button">
                            <img
                                alt="Rectangle171031"
                                src="{% static 'media/rectangle171031-rxgd-200h.png' %}"
                                class="navbar-rectangle17"
                            />
                            <span class="navbar-text4">
                                <a
                                    href="{% url 'authentication:logout' %}"
                                    >Log out</a>
                                </span>
                        </button>
                    </div>
                </nav>

                <div style="position: absolute; top: 15vh;">
                    <!-- print out every element of events json -->
                    {% for event in events %}
                    <div class="jobs-container1">
                        <div class="jobs-frame2">
                            <img
                                src="{% static event.image %}"
                                alt="Rectangle121810"
                                class="jobs-rectangle12"
                            />
                            <div class="jobs-frame14">
                                <span class="jobs-text"
                                    ><span>{{ event.name }} </span></span>
                                    <span> {{ event.countries.0.name }} - {{ event.countries.0.society_name }} </span>
                                <span class="jobs-text2">
                                    <p> {{ event.disaster_start_date }} </p>
                                    <p> Number of people affected: {{ event.num_affected }} </p>
                                    <p> Emergency response contact: {{ event.emergency_response_contact_email }}</p>
                                    <p> Severity level: {{ event.ifrc_severity_level_display }}</p>
                                </span>
                                <div class="jobs-container2">
                                    <button class="jobs-button" style="padding: 0.5em 1.5em;">
                                        <a
                                            href="{% url 'strategy:job_task' event_name=event.dtype.name %}"
                                            class="button-button"
                                        >

                                        <span class="jobs-text4">
                                            <span>View tasks</span>
                                            <br />
                                        </span>
                                        </a>
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <br />
                    {% endfor %}
                </div>
        </div>
    </body>
</html>